name: C Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #- name: Install build tools
      #  run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build the project
        run: make

      - name: Run the program with sample input
        run: |
          echo -e "10\n+\n5\n" | ./calc
          echo -e "10\n-\n5\n" | ./calc
          echo -e "10\n*\n5\n" | ./calc
          echo -e "10\n/\n5\n" | ./calc
